### ISSUE TITLE
Request: Add more cleanup for OneDrive

### ISSUE THREAD

**Issue by brmcmill** [badtutta/CacheClean#1]
Hey @badtutta -- I do think for the OneDrive option, adding these pieces will truly clean things up for OneDrive.  Sometimes that's been a challenge when users have Sync issues, so running this solution seems to fix it.  Overall awesome stuff so far!

```PowerShell
Remove-Item -Path "HKCU:\SOFTWARE\Microsoft\OneDrive" -Recurse -Force | Out-Null
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe" /reset | Out-Null
Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\OneDrive\Settings\" -Recurse -Force | Out-Null
Start-Sleep 5
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe"
```

**Comment by badtutta** [comment]
Done.

Oddly had that in first version but removed it because I thought it not needed. Good to know I was wrong.

Thanks.

Looks like the cache folder I delete for PowerBI is correct. Not sure if that is all I need though.

Also, Robert could not access system variables in his system as it was too locked down. %LOCALAPPDATA% returned nothing for him. May have been because of lock down and script may be able to bypass all that.

This is why we test.


Brad Tucker  |  Senior Consultant II |  Microsoft Services

Phone:  678-629-5224     Cell:  404-427-1435     Fax:  678-629-5271



www.microsoft.com/services<http://www.microsoft.com/services>

________________________________
From: Brandon McMillan ***@***.***>
Sent: Wednesday, March 1, 2023 7:29:43 PM
To: badtutta/CacheClean ***@***.***>
Cc: Brad Tucker ***@***.***>; Mention ***@***.***>
Subject: [badtutta/CacheClean] Request: Add more cleanup for OneDrive (Issue #1)


Hey @badtutta<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbadtutta&data=05%7C01%7Cbrad.tucker%40microsoft.com%7C5ed3c328c6e744a6350408db1abd9a3d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638133173881266874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xb0Mazn80h0wuFamUahJQ1Tp3tXsJg6bWfTtKiKTEiE%3D&reserved=0> -- I do think for the OneDrive option, adding these pieces will truly clean things up for OneDrive. Sometimes that's been a challenge when users have Sync issues, so running this solution seems to fix it. Overall awesome stuff so far!

Remove-Item -Path "HKCU:\SOFTWARE\Microsoft\OneDrive" -Recurse -Force | Out-Null
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe" /reset | Out-Null
Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\OneDrive\Settings\" -Recurse -Force | Out-Null
Start-Sleep 5
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe"

**Comment by brmcmill** [comment]
Hey @badtutta -- have an update to the OneDrive cleanup.  This might work better now for Windows 11.

----

```PowerShell
Get-Process "OneDrive" -ErrorAction SilentlyContinue | kill -Force -ErrorAction SilentlyContinue | Out-Null
Remove-Item -Path "HKCU:\SOFTWARE\Microsoft\OneDrive" -Recurse -Force -ErrorAction SilentlyContinue | Out-Null
Remove-Item -Path "$env:LOCALAPPDATA\OneDrive" -Recurse -Force -ErrorAction SilentlyContinue | Out-Null
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe" /reset | Out-Null
Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\OneDrive\Settings\" -Recurse -Force -ErrorAction SilentlyContinue | Out-Null
Start-Sleep 5
& "$env:ProgramFiles\Microsoft OneDrive\OneDrive.exe"
```

**Comment by badtutta** [comment]
Cool.  Thanks.

Will add that.  What is the verdict on using shortcuts?  Should I change them to some other mechanism or do we think we can get an exception?



Brad Tucker  |  Senior Consultant  |  Microsoft Services
Phone:  678-629-5224     Cell:  404-427-1435     Fax:  678-629-5271

www.microsoft.com/services<http://www.microsoft.com/services>

**Comment by brmcmill** [comment]
Just got back today, so I'll see if I'll check it out more tomorrow.

Best Regards,

- Brandon

**Comment by brmcmill** [comment]
This can be closed.
